//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneRecord", Namespace="https://ssa.by/")]
    [System.SerializableAttribute()]
    public partial class PhoneRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ssa.by/", ConfigurationName="ServiceReference.CollectionManagerServiceSoap")]
    public interface CollectionManagerServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetCollectionResult из пространства имен https://ssa.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/GetCollection", ReplyAction="*")]
        WebServiceClient.ServiceReference.GetCollectionResponse GetCollection(WebServiceClient.ServiceReference.GetCollectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/GetCollection", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.GetCollectionResponse> GetCollectionAsync(WebServiceClient.ServiceReference.GetCollectionRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phoneRecord из пространства имен https://ssa.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/AddElement", ReplyAction="*")]
        WebServiceClient.ServiceReference.AddElementResponse AddElement(WebServiceClient.ServiceReference.AddElementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/AddElement", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.AddElementResponse> AddElementAsync(WebServiceClient.ServiceReference.AddElementRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phoneRecord из пространства имен https://ssa.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/UpdateElement", ReplyAction="*")]
        WebServiceClient.ServiceReference.UpdateElementResponse UpdateElement(WebServiceClient.ServiceReference.UpdateElementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/UpdateElement", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.UpdateElementResponse> UpdateElementAsync(WebServiceClient.ServiceReference.UpdateElementRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phoneRecord из пространства имен https://ssa.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/DeleteElement", ReplyAction="*")]
        WebServiceClient.ServiceReference.DeleteElementResponse DeleteElement(WebServiceClient.ServiceReference.DeleteElementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ssa.by/DeleteElement", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.DeleteElementResponse> DeleteElementAsync(WebServiceClient.ServiceReference.DeleteElementRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCollectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCollection", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.GetCollectionRequestBody Body;
        
        public GetCollectionRequest() {
        }
        
        public GetCollectionRequest(WebServiceClient.ServiceReference.GetCollectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCollectionRequestBody {
        
        public GetCollectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCollectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCollectionResponse", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.GetCollectionResponseBody Body;
        
        public GetCollectionResponse() {
        }
        
        public GetCollectionResponse(WebServiceClient.ServiceReference.GetCollectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssa.by/")]
    public partial class GetCollectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServiceReference.PhoneRecord[] GetCollectionResult;
        
        public GetCollectionResponseBody() {
        }
        
        public GetCollectionResponseBody(WebServiceClient.ServiceReference.PhoneRecord[] GetCollectionResult) {
            this.GetCollectionResult = GetCollectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddElementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddElement", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.AddElementRequestBody Body;
        
        public AddElementRequest() {
        }
        
        public AddElementRequest(WebServiceClient.ServiceReference.AddElementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssa.by/")]
    public partial class AddElementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServiceReference.PhoneRecord phoneRecord;
        
        public AddElementRequestBody() {
        }
        
        public AddElementRequestBody(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            this.phoneRecord = phoneRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddElementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddElementResponse", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.AddElementResponseBody Body;
        
        public AddElementResponse() {
        }
        
        public AddElementResponse(WebServiceClient.ServiceReference.AddElementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddElementResponseBody {
        
        public AddElementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateElementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateElement", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.UpdateElementRequestBody Body;
        
        public UpdateElementRequest() {
        }
        
        public UpdateElementRequest(WebServiceClient.ServiceReference.UpdateElementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssa.by/")]
    public partial class UpdateElementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServiceReference.PhoneRecord phoneRecord;
        
        public UpdateElementRequestBody() {
        }
        
        public UpdateElementRequestBody(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            this.phoneRecord = phoneRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateElementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateElementResponse", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.UpdateElementResponseBody Body;
        
        public UpdateElementResponse() {
        }
        
        public UpdateElementResponse(WebServiceClient.ServiceReference.UpdateElementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateElementResponseBody {
        
        public UpdateElementResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteElementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteElement", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.DeleteElementRequestBody Body;
        
        public DeleteElementRequest() {
        }
        
        public DeleteElementRequest(WebServiceClient.ServiceReference.DeleteElementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ssa.by/")]
    public partial class DeleteElementRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClient.ServiceReference.PhoneRecord phoneRecord;
        
        public DeleteElementRequestBody() {
        }
        
        public DeleteElementRequestBody(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            this.phoneRecord = phoneRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteElementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteElementResponse", Namespace="https://ssa.by/", Order=0)]
        public WebServiceClient.ServiceReference.DeleteElementResponseBody Body;
        
        public DeleteElementResponse() {
        }
        
        public DeleteElementResponse(WebServiceClient.ServiceReference.DeleteElementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteElementResponseBody {
        
        public DeleteElementResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CollectionManagerServiceSoapChannel : WebServiceClient.ServiceReference.CollectionManagerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollectionManagerServiceSoapClient : System.ServiceModel.ClientBase<WebServiceClient.ServiceReference.CollectionManagerServiceSoap>, WebServiceClient.ServiceReference.CollectionManagerServiceSoap {
        
        public CollectionManagerServiceSoapClient() {
        }
        
        public CollectionManagerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollectionManagerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectionManagerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollectionManagerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference.GetCollectionResponse WebServiceClient.ServiceReference.CollectionManagerServiceSoap.GetCollection(WebServiceClient.ServiceReference.GetCollectionRequest request) {
            return base.Channel.GetCollection(request);
        }
        
        public WebServiceClient.ServiceReference.PhoneRecord[] GetCollection() {
            WebServiceClient.ServiceReference.GetCollectionRequest inValue = new WebServiceClient.ServiceReference.GetCollectionRequest();
            inValue.Body = new WebServiceClient.ServiceReference.GetCollectionRequestBody();
            WebServiceClient.ServiceReference.GetCollectionResponse retVal = ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).GetCollection(inValue);
            return retVal.Body.GetCollectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.GetCollectionResponse> WebServiceClient.ServiceReference.CollectionManagerServiceSoap.GetCollectionAsync(WebServiceClient.ServiceReference.GetCollectionRequest request) {
            return base.Channel.GetCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference.GetCollectionResponse> GetCollectionAsync() {
            WebServiceClient.ServiceReference.GetCollectionRequest inValue = new WebServiceClient.ServiceReference.GetCollectionRequest();
            inValue.Body = new WebServiceClient.ServiceReference.GetCollectionRequestBody();
            return ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).GetCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference.AddElementResponse WebServiceClient.ServiceReference.CollectionManagerServiceSoap.AddElement(WebServiceClient.ServiceReference.AddElementRequest request) {
            return base.Channel.AddElement(request);
        }
        
        public void AddElement(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            WebServiceClient.ServiceReference.AddElementRequest inValue = new WebServiceClient.ServiceReference.AddElementRequest();
            inValue.Body = new WebServiceClient.ServiceReference.AddElementRequestBody();
            inValue.Body.phoneRecord = phoneRecord;
            WebServiceClient.ServiceReference.AddElementResponse retVal = ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).AddElement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.AddElementResponse> WebServiceClient.ServiceReference.CollectionManagerServiceSoap.AddElementAsync(WebServiceClient.ServiceReference.AddElementRequest request) {
            return base.Channel.AddElementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference.AddElementResponse> AddElementAsync(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            WebServiceClient.ServiceReference.AddElementRequest inValue = new WebServiceClient.ServiceReference.AddElementRequest();
            inValue.Body = new WebServiceClient.ServiceReference.AddElementRequestBody();
            inValue.Body.phoneRecord = phoneRecord;
            return ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).AddElementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference.UpdateElementResponse WebServiceClient.ServiceReference.CollectionManagerServiceSoap.UpdateElement(WebServiceClient.ServiceReference.UpdateElementRequest request) {
            return base.Channel.UpdateElement(request);
        }
        
        public void UpdateElement(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            WebServiceClient.ServiceReference.UpdateElementRequest inValue = new WebServiceClient.ServiceReference.UpdateElementRequest();
            inValue.Body = new WebServiceClient.ServiceReference.UpdateElementRequestBody();
            inValue.Body.phoneRecord = phoneRecord;
            WebServiceClient.ServiceReference.UpdateElementResponse retVal = ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).UpdateElement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.UpdateElementResponse> WebServiceClient.ServiceReference.CollectionManagerServiceSoap.UpdateElementAsync(WebServiceClient.ServiceReference.UpdateElementRequest request) {
            return base.Channel.UpdateElementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference.UpdateElementResponse> UpdateElementAsync(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            WebServiceClient.ServiceReference.UpdateElementRequest inValue = new WebServiceClient.ServiceReference.UpdateElementRequest();
            inValue.Body = new WebServiceClient.ServiceReference.UpdateElementRequestBody();
            inValue.Body.phoneRecord = phoneRecord;
            return ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).UpdateElementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference.DeleteElementResponse WebServiceClient.ServiceReference.CollectionManagerServiceSoap.DeleteElement(WebServiceClient.ServiceReference.DeleteElementRequest request) {
            return base.Channel.DeleteElement(request);
        }
        
        public void DeleteElement(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            WebServiceClient.ServiceReference.DeleteElementRequest inValue = new WebServiceClient.ServiceReference.DeleteElementRequest();
            inValue.Body = new WebServiceClient.ServiceReference.DeleteElementRequestBody();
            inValue.Body.phoneRecord = phoneRecord;
            WebServiceClient.ServiceReference.DeleteElementResponse retVal = ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).DeleteElement(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference.DeleteElementResponse> WebServiceClient.ServiceReference.CollectionManagerServiceSoap.DeleteElementAsync(WebServiceClient.ServiceReference.DeleteElementRequest request) {
            return base.Channel.DeleteElementAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference.DeleteElementResponse> DeleteElementAsync(WebServiceClient.ServiceReference.PhoneRecord phoneRecord) {
            WebServiceClient.ServiceReference.DeleteElementRequest inValue = new WebServiceClient.ServiceReference.DeleteElementRequest();
            inValue.Body = new WebServiceClient.ServiceReference.DeleteElementRequestBody();
            inValue.Body.phoneRecord = phoneRecord;
            return ((WebServiceClient.ServiceReference.CollectionManagerServiceSoap)(this)).DeleteElementAsync(inValue);
        }
    }
}
